---
##
# PHP Debugging tools
#
- name: Installing XDebug
  apt: pkg={{ item }} state=present
  with_items: "{{ php_xdebug_apt_packages }}"
  when: php_xdebug_enable

- name: Adding XHProf PPA Repository
  apt_repository: repo=ppa:brianmercer/php5-xhprof
  register: result
  when: php_xhprof_enable and ansible_distribution_version == "12.04"

- name: Installing XHProf
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - php5-xhprof
    - graphviz
  when: php_xhprof_enable

- name: Customizing php.ini settings.
  template: src={{ item }}-ini.j2 dest={{ php_conf_path }}/{{ item }}.ini mode=644
  with_items:
    - xdebug
    - xhprof
  notify: restart PHP server