---
- name: restart PHP server
  service: "name={{ php_daemon }} state=restarted"
  when: php_daemon != false

- name: enable ansible config
  command: "{{ phpenmod_bin }} ansible"
  when: ansible_distribution_version != "12.04"
